# Generated by Django 4.2.13 on 2024-07-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_video_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
