# Generated by Django 4.2.13 on 2024-07-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
    ]
